# Program to Implement Page Rank Algorithm


In [68]:
import numpy as np
n=int(input('Enter the number of nodes: '))
y=[]
dict1={}
beta=0.85
for i in range(0,n):
    print('Enter the transition values of node {0}'.format(i+1))
    x=list(map(int,input().split()))
    y.append(x)
    dict1.update({i:0})
for i in y:
    for j in range(0,n):
        if(i[j]==1):
            dict1[j]+=1
for i in range(0,n):
    for j in range(0,n):
        if dict1[j] !=0:
            y[i][j]=y[i][j]/dict1[j]
y=np.matrix(y)
v_zero=np.ones([n,1])
prev=np.ones([n,1])
for i in range(1,100):
    v_zero=(beta*y*v_zero)+((1-beta)*(np.ones([n,1])/n))
    if(prev==v_zero).all():
        break
    prev=v_zero
print(v_zero)

        
        
        

Enter the number of nodes: 3
Enter the transition values of node 1
0 1 1
Enter the transition values of node 2
1 0 0
Enter the transition values of node 3
1 0 0
[[0.48648664]
 [0.25675678]
 [0.25675678]]


In [45]:
const

array([[0.025],
       [0.025],
       [0.025],
       [0.025],
       [0.025],
       [0.025]])

In [57]:
v_zero=np.ones([1,3])/n

In [58]:
v_zero*(1-beta)

array([[0.025, 0.025, 0.025]])